### ISSUE TITLE
Does this work on iOS 7.1?

### ISSUE THREAD

**Issue by Perjan** [venmo/VENTouchLock#29]
I wonder if it works on iOS 7.1, because on the simulator the demo fails with message: 

"dyld: Symbol not found: _objc_isAuto
  Referenced from: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/usr/lib/libobjc.A.dylib
 in /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
"

**Comment by dasmer** [comment]
This seems like an Xcode framework import issue. I was not able to replicate on Xcode 6
